name: JavaScript Linting
on:
  push:
    branches-ignore:
      - 'dependabot/**'
      - 'renovate/**'
    paths:
      - 'package.json'
      - 'yarn.lock'
      - 'tsconfig.json'
      - '.nvmrc'
      - '.prettier*'
      - '.eslint*'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.tsx'
      - '.github/workflows/lint-js.yml'

  pull_request:
    paths:
      - 'package.json'
      - 'yarn.lock'
      - 'tsconfig.json'
      - '.nvmrc'
      - '.prettier*'
      - '.eslint*'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.tsx'
      - '.github/workflows/lint-js.yml'

jobs:
  lint:
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:js-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Javascript environment
        uses: ./.github/actions/setup-javascript

      - name: ESLint
        run: yarn lint:js --max-warnings 0

      - name: Typecheck
        run: yarn typecheck
